# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailyFresh' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DailyFresh
    pod 'AFNetworking',     '~>3.2.1'
    pod 'Masonry',          '~>1.1.0'
    pod 'SDWebImage',       '~>4.4.3'
    pod 'SDAutoLayout',     '~> 2.2.1'
    pod 'MJRefresh',        '~>3.1.15.7'
    pod 'FMDB',             '~>2.7.5'
    pod 'YYModel',          '~>1.0.4'
    pod 'MJExtension',      '~>3.0.15.1'
    #pod 'TZImagePickerController', '~> 3.1.5'
    pod 'SDCycleScrollView','~> 1.75'
    pod 'YYText',          '~>1.0.7'
    pod 'YYCategories',          '~>1.0.4'
    #pod 'IQKeyboardManager', '~> 6.2.0'
    pod 'LBXScan/LBXNative','~> 2.3'
    pod 'LBXScan/UI','~> 2.3'

  target 'DailyFreshTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DailyFreshUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
